"use client";

import { useMemo, useState } from "react";

type Role = "client" | "lawyer" | "admin";
type Lawyer = { id:number; name:string; initials:string; field:string; city:string; rating:number; reviews:number; consults:number; price:string; online:boolean; featured?:boolean; color:string; bio:string };
const lawyers: Lawyer[] = [
  {id:1,name:"دکتر نازنین فرهمند",initials:"نف",field:"خانواده و طلاق",city:"تهران",rating:4.9,reviews:214,consults:486,price:"۴۸۰ هزار تومان",online:true,featured:true,color:"#d8eadf",bio:"وکیل پایه یک دادگستری با ۱۲ سال تجربه در پرونده‌های خانواده، مهریه و حضانت."},
  {id:2,name:"امیرحسین دادخواه",initials:"اد",field:"دعاوی کیفری",city:"شیراز",rating:4.8,reviews:176,consults:391,price:"۵۵۰ هزار تومان",online:true,featured:true,color:"#e9dfcf",bio:"متخصص پرونده‌های کیفری، جرایم رایانه‌ای و دفاع در دادسرا و دادگاه."},
  {id:3,name:"سارا نیک‌اندیش",initials:"سن",field:"ملکی و قراردادها",city:"اصفهان",rating:4.7,reviews:142,consults:328,price:"۴۲۰ هزار تومان",online:false,color:"#d9e5ef",bio:"مشاور حقوقی قراردادها و دعاوی ملکی با رویکرد دقیق و راه‌حل‌محور."},
  {id:4,name:"محمدرضا توکلی",initials:"مت",field:"تجاری و شرکت‌ها",city:"تهران",rating:4.9,reviews:121,consults:274,price:"۶۲۰ هزار تومان",online:true,featured:true,color:"#e4dcec",bio:"مشاور کسب‌وکارها در ثبت شرکت، قراردادهای تجاری و اختلاف شرکا."},
  {id:5,name:"الهام رستگار",initials:"ار",field:"ارث و امور ثبتی",city:"تبریز",rating:4.6,reviews:98,consults:219,price:"۳۹۰ هزار تومان",online:false,color:"#eadbd8",bio:"پیگیری تخصصی انحصار وراثت، تقسیم ترکه و پرونده‌های ثبتی."},
];
const questions = [
  {topic:"خانواده",q:"برای مطالبه مهریه از کجا شروع کنم؟",a:"ابتدا می‌توانید از طریق اجرای ثبت اقدام کنید. اگر مالی شناسایی نشود، دادخواست مطالبه مهریه در دادگاه خانواده مطرح می‌شود.",lawyer:"دکتر نازنین فرهمند",date:"امروز"},
  {topic:"ملکی",q:"قرارداد اجاره بدون کد رهگیری اعتبار دارد؟",a:"بله، نبود کد رهگیری به‌تنهایی قرارداد را بی‌اعتبار نمی‌کند؛ اما اثبات تاریخ و مفاد قرارداد اهمیت زیادی دارد.",lawyer:"سارا نیک‌اندیش",date:"دیروز"},
  {topic:"کار و بیمه",q:"حق سنوات بعد از استعفا پرداخت می‌شود؟",a:"بله، سنوات به نسبت مدت کارکرد و آخرین حقوق محاسبه می‌شود و استعفا مانع دریافت آن نیست.",lawyer:"محمدرضا توکلی",date:"۲ روز پیش"},
];
const services = [["کیفری","دفاع حرفه‌ای در شکایات و پرونده‌های کیفری","§"],["خانواده","همراهی در طلاق، مهریه و حضانت","♡"],["ملکی","حل اختلافات ملک، سند و سرقفلی","⌂"],["تجاری","قراردادها و اختلافات کسب‌وکار","▤"],["چک و اسناد","پیگیری چک، سفته و مطالبات","✓"],["ارث","انحصار وراثت و تقسیم دارایی‌ها","♢"]];
const articles = [{tag:"خانواده",title:"راهنمای ساده مطالبه مهریه در سال ۱۴۰۵",text:"از مدارک لازم تا انتخاب مسیر اجرای ثبت یا دادگاه خانواده.",date:"۲۸ مرداد ۱۴۰۵"},{tag:"قرارداد",title:"۷ بند مهم پیش از امضای قرارداد",text:"تعهدات، خسارت و شرایط فسخ را درست و روشن بنویسید.",date:"۲۱ مرداد ۱۴۰۵"},{tag:"ملکی",title:"استعلام‌های ضروری پیش از خرید ملک",text:"چک‌لیست بررسی سند، بازداشت، بدهی و هویت فروشنده.",date:"۱۵ مرداد ۱۴۰۵"}];
const accounts:Record<string,{password:string;role:Role;name:string}>={client:{password:"Client123!",role:"client",name:"علی رضایی"},lawyer:{password:"Lawyer123!",role:"lawyer",name:"دکتر نازنین فرهمند"},admin:{password:"Admin123!",role:"admin",name:"مدیر اصلی"}};

function Logo(){return <button className="brand" onClick={()=>location.reload()}><span>د</span><b>دادراه</b></button>}
function Avatar({lawyer,small=false}:{lawyer:Lawyer;small?:boolean}){return <div className={small?"avatar small":"avatar"} style={{background:lawyer.color}}>{lawyer.initials}</div>}

export default function DadrahApp(){
 const [page,setPage]=useState("home"),[selected,setSelected]=useState(lawyers[0]),[modal,setModal]=useState<string|null>(null),[user,setUser]=useState<{role:Role;name:string}|null>(null),[toast,setToast]=useState(""),[saved,setSaved]=useState<number[]>([3]),[query,setQuery]=useState(""),[specialty,setSpecialty]=useState("همه تخصص‌ها"),[answer,setAnswer]=useState(questions[0]);
 const go=(p:string)=>{setPage(p);setModal(null);scrollTo({top:0,behavior:"smooth"})};
 const notify=(t:string)=>{setToast(t);setTimeout(()=>setToast(""),3200)};
 const reserve=(l:Lawyer)=>{setSelected(l);go("lawyer")};
 const save=(id:number)=>{setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);notify(saved.includes(id)?"از نشان‌شده‌ها حذف شد":"به نشان‌شده‌ها اضافه شد")};
 const filtered=useMemo(()=>lawyers.filter(l=>(specialty==="همه تخصص‌ها"||l.field.includes(specialty))&&(l.name.includes(query)||l.field.includes(query))),[query,specialty]);
 return <><header className="topbar"><div className="nav-shell"><Logo/><nav><button onClick={()=>go("lawyers")}>وکلا</button><button onClick={()=>{go("home");setTimeout(()=>document.getElementById("services")?.scrollIntoView({behavior:"smooth"}),50)}}>خدمات تخصصی</button><button onClick={()=>go("questions")}>پرسش‌های حقوقی</button><button onClick={()=>go("blog")}>مجله حقوقی</button><button onClick={()=>go("about")}>درباره ما</button><button onClick={()=>go("contact")}>تماس با ما</button></nav><div className="nav-actions"><button className="ask-mini" onClick={()=>setModal("ask")}>پرسش رایگان</button>{user?<button className="user-pill" onClick={()=>go("dashboard")}>{user.name.split(" ")[0]} <span>⌄</span></button>:<button className="login" onClick={()=>setModal("login")}>ورود / ثبت‌نام</button>}</div></div></header>
 <main>{page==="home"&&<Home go={go} reserve={reserve} save={save} saved={saved} ask={()=>setModal("ask")} show={(q:any)=>{setAnswer(q);setModal("answer")}}/>}{page==="lawyers"&&<Lawyers list={filtered} query={query} setQuery={setQuery} specialty={specialty} setSpecialty={setSpecialty} reserve={reserve} save={save} saved={saved} ask={()=>setModal("ask")}/>} {page==="lawyer"&&<LawyerPage lawyer={selected} pay={setModal} save={save} saved={saved} notify={notify}/>} {page==="questions"&&<Questions ask={()=>setModal("ask")} show={(q:any)=>{setAnswer(q);setModal("answer")}}/>}{page==="blog"&&<Blog/>}{page==="about"&&<About/>}{page==="contact"&&<Contact notify={notify}/>} {page==="dashboard"&&<Dashboard user={user} go={go} logout={()=>{setUser(null);go("home");notify("با موفقیت خارج شدید")}}/>}</main>
 {page!=="dashboard"&&<Footer go={go}/>} {modal&&<Modal name={modal} close={()=>setModal(null)} selected={selected} login={(u:string,p:string)=>{const a=accounts[u];if(a&&a.password===p){setUser({role:a.role,name:a.name});setModal(null);notify("خوش آمدید؛ وارد حساب شدید")}else notify("نام کاربری یا رمز عبور درست نیست")}} notify={notify} go={go} answer={answer}/>} {toast&&<div className="toast"><span>✓</span>{toast}</div>}</>;
}

function Home({go,reserve,save,saved,ask,show}:any){return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><i/> بیش از ۴۸ وکیل تأییدشده کنار شما هستند</span><h1>برای مسئله حقوقی‌ات،<br/><em>راه روشن</em> پیدا کن.</h1><p>موضوعت را ساده بگو؛ وکیل متخصص را انتخاب کن یا انتخاب را به ما بسپار. پاسخ اولیه رایگان است.</p><div className="hero-actions"><button className="primary" onClick={ask}>پرسش حقوقی رایگان <span>←</span></button><button className="ghost" onClick={()=>go("lawyers")}>مشاهده وکلا</button></div><div className="proof"><div><b>+۱۲ هزار</b><span>پاسخ حقوقی</span></div><div><b>۹۴٪</b><span>رضایت کاربران</span></div><div><b>کمتر از ۱ ساعت</b><span>میانگین پاسخ</span></div></div></div><div className="hero-scene"><div className="consult-card"><div className="live"><i/> آماده پاسخ‌گویی</div><Avatar lawyer={lawyers[0]}/><h3>{lawyers[0].name}</h3><p>{lawyers[0].field}</p><div className="rating">★ {lawyers[0].rating} <small>({lawyers[0].reviews} نظر)</small></div><button onClick={()=>reserve(lawyers[0])}>رزرو مشاوره</button></div><div className="floating-note"><span>✓</span><div><b>درخواست ثبت شد</b><small>وکیل تا کمتر از یک ساعت تماس می‌گیرد</small></div></div></div></section><div className="quick-tabs"><a href="#top-lawyers">وکلای برتر</a><a href="#services">خدمات</a><a href="#reviews">تجربه کاربران</a><a href="#faq">سؤالات متداول</a><a href="#latest">پرسش‌های تازه</a></div>
 <section className="section" id="top-lawyers"><SectionHead kicker="انتخاب مطمئن" title="وکلایی که کاربران پیشنهاد کرده‌اند" text="بر اساس تخصص، تجربه و رضایت موکلان انتخاب شده‌اند." action="همه وکلا" onAction={()=>go("lawyers")}/><div className="lawyer-grid">{lawyers.slice(0,4).map(l=><LawyerCard key={l.id} lawyer={l} reserve={reserve} save={save} saved={saved}/>)}</div></section>
 <section className="section alt" id="services"><SectionHead kicker="هر مسئله، یک متخصص" title="در چه زمینه‌ای به راهنمایی نیاز دارید؟" text="موضوع را انتخاب کنید تا مستقیم به وکیل همان حوزه برسید."/><div className="service-grid">{services.map((s,i)=><button className="service" key={i} onClick={()=>go("lawyers")}><span>{s[2]}</span><h3>{s[0]}</h3><p>{s[1]}</p><i>مشاهده وکلا ←</i></button>)}</div></section>
 <section className="steps"><div><span className="eyebrow light">از مسئله تا راه‌حل</span><h2>سه قدم کوتاه،<br/>بدون سردرگمی</h2><p>ما بخش سخت پیدا کردن وکیل مناسب را ساده کرده‌ایم.</p><button className="gold" onClick={ask}>همین حالا شروع کن</button></div><ol><li><b>۰۱</b><div><h3>مسئله‌ات را بگو</h3><p>موضوع و توضیح کوتاهی از شرایطت بنویس.</p></div></li><li><b>۰۲</b><div><h3>وکیل مناسب را پیدا کن</h3><p>خودت انتخاب کن یا پیشنهاد تخصصی ما را ببین.</p></div></li><li><b>۰۳</b><div><h3>پاسخ بگیر و ادامه بده</h3><p>رایگان سؤال بپرس یا وقت مشاوره رزرو کن.</p></div></li></ol></section>
 <section className="section" id="latest"><SectionHead kicker="دانش حقوقی برای همه" title="پرسش‌های تازه کاربران" text="پاسخ‌های کوتاه و کاربردی وکلای دادراه." action="نمایش همه" onAction={()=>go("questions")}/><div className="question-grid">{questions.map((q,i)=><article className="q-card" key={i}><div><span>{q.topic}</span><small>{q.date}</small></div><h3>{q.q}</h3><p>پاسخ داده شده توسط {q.lawyer}</p><button onClick={()=>show(q)}>مشاهده پاسخ ←</button></article>)}</div></section>
 <section className="testimonial" id="reviews"><div><span>“</span><p>برای یک موضوع ملکی واقعاً سردرگم بودم. کمتر از نیم ساعت با وکیل متخصص صحبت کردم و دقیقاً فهمیدم قدم بعدی چیست.</p><div><b>مریم شریفی</b><small>مشاوره ملکی · امتیاز ۵ از ۵</small></div></div><aside><b>۴.۸ از ۵</b><span>میانگین امتیاز کاربران</span><div>★★★★★</div></aside></section>
 <section className="section faq" id="faq"><SectionHead kicker="پاسخ روشن" title="چیزهایی که احتمالاً می‌خواهید بدانید"/><details open><summary>اطلاعات و مدارک من محرمانه می‌ماند؟</summary><p>بله. اطلاعات شما فقط در اختیار وکیل مربوط و تیم پشتیبانی مجاز قرار می‌گیرد.</p></details><details><summary>اگر ندانم کدام وکیل مناسب من است چه؟</summary><p>موضوع را رایگان ثبت کنید؛ مدیر پرونده آن را به وکلای مرتبط ارجاع می‌دهد.</p></details><details><summary>مشاوره تلفنی چقدر طول می‌کشد؟</summary><p>هر جلسه تا ۳۰ دقیقه است و معمولاً تماس در بازه یک دقیقه تا یک ساعت انجام می‌شود.</p></details></section><section className="cta"><div><span>هنوز مطمئن نیستی از کجا شروع کنی؟</span><h2>موضوعت را بگو؛ ادامه مسیر با ما.</h2></div><button onClick={ask}>ثبت پرسش رایگان ←</button></section></>}

function SectionHead({kicker,title,text,action,onAction}:any){return <div className="section-head"><div><span>{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>{action&&<button onClick={onAction}>{action} ←</button>}</div>}
function LawyerCard({lawyer,reserve,save,saved}:any){return <article className="lawyer-card"><div className="photo"><Avatar lawyer={lawyer}/>{lawyer.online&&<span className="online"><i/> آنلاین</span>}<button className={saved.includes(lawyer.id)?"bookmark active":"bookmark"} title="نشان کردن" onClick={()=>save(lawyer.id)}>♡</button></div><div className="lawyer-info"><div>{lawyer.featured&&<span className="badge">پیشنهاد کاربران</span>}<span className="rating">★ {lawyer.rating}</span></div><h3>{lawyer.name}</h3><p>{lawyer.field} · {lawyer.city}</p><div className="stats"><span><b>{lawyer.consults}</b> مشاوره</span><span><b>{lawyer.reviews}</b> نظر</span></div><div className="price"><small>شروع مشاوره از</small><b>{lawyer.price}</b></div><button className="card-action" onClick={()=>reserve(lawyer)}>مشاهده و رزرو وقت ←</button></div></article>}

function Lawyers({list,query,setQuery,specialty,setSpecialty,reserve,save,saved,ask}:any){return <div className="page"><div className="page-hero"><span>انتخاب آگاهانه</span><h1>وکیل مناسب مسئله شما</h1><p>میان وکلای تأییدشده جست‌وجو کنید یا انتخاب را به ما بسپارید.</p><button onClick={ask}>نمی‌دانم کدام وکیل مناسب است</button></div><div className="filterbar"><label>جست‌وجو<input value={query} onChange={(e:any)=>setQuery(e.target.value)} placeholder="نام وکیل یا تخصص..."/></label><label>تخصص<select value={specialty} onChange={(e:any)=>setSpecialty(e.target.value)}><option>همه تخصص‌ها</option><option>خانواده</option><option>کیفری</option><option>ملکی</option><option>تجاری</option></select></label><label>مرتب‌سازی<select><option>پیشنهاد کاربران</option><option>بیشترین امتیاز</option><option>کمترین هزینه</option></select></label></div><div className="results"><p><b>{list.length}</b> وکیل پیدا شد</p><div className="lawyer-grid">{list.map((l:Lawyer)=><LawyerCard key={l.id} lawyer={l} reserve={reserve} save={save} saved={saved}/>)}</div></div></div>}

function LawyerPage({lawyer,pay,save,saved,notify}:any){const [day,setDay]=useState("شنبه ۸ شهریور");return <div className="page lawyer-page"><div className="profile-layout"><section className="profile-main"><div className="profile-head"><Avatar lawyer={lawyer}/><div><div className="chips">{lawyer.featured&&<span>پیشنهاد کاربران</span>}{lawyer.online&&<span className="green">● آماده پاسخ‌گویی</span>}</div><h1>{lawyer.name}</h1><p>{lawyer.field} · وکیل پایه یک دادگستری · {lawyer.city}</p><div className="profile-rating"><b>★ {lawyer.rating}</b><span>{lawyer.reviews} نظر تأییدشده</span></div></div><button className="save-profile" onClick={()=>save(lawyer.id)}>{saved.includes(lawyer.id)?"نشان شده":"♡ نشان کردن"}</button></div><div className="bio"><h2>درباره وکیل</h2><p>{lawyer.bio} هدف او ارائه راهکار شفاف و متناسب با شرایط هر موکل است.</p></div><div className="performance"><div><b>{lawyer.consults}</b><span>مشاوره موفق</span></div><div><b>{lawyer.reviews}</b><span>نظر کاربران</span></div><div><b>۱۲ سال</b><span>سابقه حرفه‌ای</span></div><div><b>۹۶٪</b><span>رضایت موکلان</span></div></div><h2>انتخاب نوع مشاوره</h2><div className="consult-options"><button onClick={()=>pay("phone")}><span>☎</span><div><b>مشاوره تلفنی</b><small>تماس تا حداکثر یک ساعت</small></div><strong>{lawyer.price}</strong></button><button onClick={()=>pay("text")}><span>□</span><div><b>گفت‌وگوی متنی</b><small>پرسش و پاسخ امن با وکیل</small></div><strong>۳۲۰ هزار تومان</strong></button></div></section><aside className="booking"><span className="label">رزرو حضوری</span><h2>زمان مناسب را انتخاب کنید</h2><p>دفتر {lawyer.name}، {lawyer.city}</p><div className="days">{["شنبه ۸ شهریور","یکشنبه ۹ شهریور","دوشنبه ۱۰ شهریور"].map(d=><button className={day===d?"active":""} onClick={()=>setDay(d)} key={d}>{d}</button>)}</div><div className="times"><button>۱۰:۳۰</button><button>۱۲:۰۰</button><button>۱۶:۳۰</button><button disabled>۱۸:۰۰</button></div><div className="booking-price"><span>هزینه جلسه حضوری</span><b>۸۵۰ هزار تومان</b></div><button className="primary wide" onClick={()=>notify("نوبت حضوری شما با موفقیت ثبت شد")}>رزرو و پرداخت آزمایشی</button><small className="secure">✓ در نسخه آزمایشی مبلغی کسر نمی‌شود</small></aside></div></div>}

function Questions({ask,show}:any){return <div className="page"><div className="page-hero left-action"><div><span>پاسخ‌های قابل اعتماد</span><h1>پرسش‌های حقوقی کاربران</h1><p>میان پاسخ‌های وکلای دادراه جست‌وجو کنید.</p></div><button onClick={ask}>+ ثبت پرسش رایگان</button></div><div className="question-page-list">{[...questions,...questions].map((q,i)=><article key={i}><span>{q.topic}</span><h2>{q.q}</h2><p>{q.a.slice(0,105)}...</p><div><small>{q.lawyer} · {q.date}</small><button onClick={()=>show(q)}>پاسخ کامل ←</button></div></article>)}</div></div>}
function Blog(){return <div className="page"><div className="page-hero"><span>مجله دادراه</span><h1>حقوق، به زبان قابل فهم</h1><p>راهنماهای کاربردی برای تصمیم‌های حقوقی روزمره.</p></div><div className="article-grid">{[...articles,...articles].map((a,i)=><article key={i}><div className={`article-cover c${i%3}`}><span>دادراه</span></div><div><span>{a.tag}</span><h2>{a.title}</h2><p>{a.text}</p><small>{a.date} · ۶ دقیقه مطالعه</small><button>مطالعه مقاله ←</button></div></article>)}</div></div>}
function About(){return <div className="page prose-page"><div className="page-hero"><span>درباره دادراه</span><h1>حقوق نباید پیچیده و دور از دسترس باشد</h1><p>کمک می‌کنیم هرکس، هرجای ایران، با اطمینان به وکیل متخصص برسد.</p></div><section><h2>راهی روشن‌تر برای مسائل حقوقی</h2><p>دادراه یک تیم متعهد از متخصصان حقوق و فناوری است. مسیر پیدا کردن وکیل، مطرح کردن مسئله و پیگیری مشاوره را ساده کرده‌ایم.</p><div className="value-grid"><div><b>وکلای تأییدشده</b><p>هویت و پروانه هر وکیل پیش از نمایش بررسی می‌شود.</p></div><div><b>حریم خصوصی واقعی</b><p>اسناد و گفتگوها فقط در اختیار افراد مجاز است.</p></div><div><b>پشتیبانی تا پایان مسیر</b><p>تیم ما وضعیت هر درخواست را تا رسیدن به نتیجه پیگیری می‌کند.</p></div></div></section></div>}
function Contact({notify}:any){return <div className="page contact-page"><div><span className="eyebrow">ما کنار شماییم</span><h1>چطور می‌توانیم کمک کنیم؟</h1><p>برای پیگیری درخواست، همکاری یا هر سؤال دیگری پیام بگذارید.</p><div className="contact-info"><div><b>تماس</b><span>۰۲۱-۹۱۰۹ ۲۰۲۰</span></div><div><b>ایمیل</b><span>support@dadrah.ir</span></div><div><b>نشانی</b><span>تهران، میدان ونک، خیابان ملاصدرا</span></div></div></div><form onSubmit={(e:any)=>{e.preventDefault();notify("پیام شما ثبت شد و در پنل مدیریت قرار گرفت");e.target.reset()}}><h2>برای ما بنویسید</h2><label>نام و نام خانوادگی<input required placeholder="مثلاً علی رضایی"/></label><label>شماره همراه<input required placeholder="۰۹۱۲۱۲۳۴۵۶۷"/></label><label>موضوع<select><option>پشتیبانی درخواست</option><option>شکایت یا انتقاد</option><option>همکاری با دادراه</option></select></label><label>پیام<textarea required rows={5} placeholder="چطور می‌توانیم کمک کنیم؟"/></label><button className="primary">ارسال پیام</button></form></div>}

function Dashboard({user,go,logout}:any){const role:Role=user?.role||"client";const [tab,setTab]=useState(role==="admin"?"overview":"profile");const menus=role==="admin"?[["overview","نمای کلی"],["lawyers","تأیید وکلا"],["users","کاربران"],["assign","ارجاع پرسش‌ها"],["content","محتوا و وبلاگ"],["finance","مالی و تنظیمات"],["messages","پیام‌ها و شکایات"]]:role==="lawyer"?[["profile","پروفایل حرفه‌ای"],["requests","درخواست‌های مشاوره"],["questions","پرسش‌های کاربران"],["schedule","زمان‌های رزرو"],["reviews","نظرها و عملکرد"]]:[["profile","اطلاعات فردی"],["orders","سفارش‌های من"],["consults","مشاوره‌های من"],["questions","پرسش‌های من"],["saved","نشان‌شده‌ها"],["complaint","ثبت شکایت"]];return <div className="dashboard"><aside><Logo/><div className="dash-user"><div>{user?.name?.slice(0,1)||"ک"}</div><span><b>{user?.name||"کاربر آزمایشی"}</b><small>{role==="admin"?"مدیر اصلی":role==="lawyer"?"وکیل تأییدشده":"موکل"}</small></span></div><nav>{menus.map(m=><button key={m[0]} className={tab===m[0]?"active":""} onClick={()=>setTab(m[0])}>{m[1]}<span>←</span></button>)}</nav><button className="dash-back" onClick={()=>go("home")}>بازگشت به سایت</button><button className="logout" onClick={logout}>خروج از حساب</button></aside><section className="dash-content"><header><div><span>{new Intl.DateTimeFormat("fa-IR",{dateStyle:"full"}).format(new Date())}</span><h1>{tabTitle(tab,role)}</h1></div>{role==="lawyer"&&<label className="availability"><input type="checkbox" defaultChecked/> آماده پاسخ‌گویی هستم</label>}<button className="notice">◌<i>۳</i></button></header><DashboardContent role={role} tab={tab}/></section></div>}
function tabTitle(tab:string,role:Role){const x:any={overview:"سلام، امروز چه خبر؟",lawyers:"بررسی و تأیید وکلا",users:"مدیریت کاربران",assign:"ارجاع پرسش‌های جدید",content:"مدیریت محتوا",finance:"گزارش مالی",messages:"پیام‌ها و شکایات",profile:role==="lawyer"?"پروفایل حرفه‌ای من":"اطلاعات فردی",requests:"درخواست‌های مشاوره",questions:role==="lawyer"?"پرسش‌های ارجاع‌شده":"پرسش‌های من",schedule:"تقویم و زمان‌های آزاد",reviews:"عملکرد و نظرها",orders:"سفارش‌های من",consults:"مشاوره‌های من",saved:"وکلای نشان‌شده",complaint:"ثبت شکایت"};return x[tab]||"پنل کاربری"}
function DashboardContent({role,tab}:any){if(role==="admin")return <AdminContent tab={tab}/>;if(tab==="profile")return <div className="panel"><h2>مشخصات {role==="lawyer"?"فردی و حرفه‌ای":"فردی"}</h2><div className="form-grid"><label>نام<input defaultValue={role==="lawyer"?"نازنین":"علی"}/></label><label>نام خانوادگی<input defaultValue={role==="lawyer"?"فرهمند":"رضایی"}/></label><label>شماره همراه<input defaultValue="۰۹۱۲۱۲۳۴۵۶۷"/></label><label>ایمیل<input defaultValue={role==="lawyer"?"lawyer@dadrah.ir":"client@dadrah.ir"}/></label><label>استان<select><option>تهران</option></select></label><label>شهر<input defaultValue="تهران"/></label>{role==="lawyer"&&<><label>شماره پروانه<input defaultValue="۲۳۴۵۶"/></label><label>تخصص اصلی<select><option>خانواده و طلاق</option></select></label></>}</div><button className="primary">ذخیره تغییرات</button></div>;const rows=role==="lawyer"?["مشاوره تلفنی با علی رضایی","پرسش عمومی درباره قرارداد اجاره","رزرو حضوری مریم احمدی"]:["مشاوره تلفنی با دکتر فرهمند","پرسش درباره قرارداد اجاره","رزرو حضوری با سارا نیک‌اندیش"];return <div className="panel"><div className="panel-head"><div><h2>{tabTitle(tab,role)}</h2><p>آخرین موارد و وضعیت پیگیری را اینجا می‌بینید.</p></div><button className="outline">+ مورد جدید</button></div><div className="data-list">{rows.map((r:string,i:number)=><div key={r}><span className={`status s${i}`}>{i===0?"در انتظار":i===1?"پاسخ داده شده":"تأیید شده"}</span><div><b>{r}</b><small>ثبت شده در {i+3} شهریور ۱۴۰۵ · کد #{2840+i}</small></div><button>مشاهده ←</button></div>)}</div></div>}
function AdminContent({tab}:any){if(tab==="overview")return <><div className="metric-grid"><div><span>درخواست‌های امروز</span><b>۲۸</b><small>۱۲٪ بیشتر از دیروز</small></div><div><span>وکلای در انتظار تأیید</span><b>۷</b><small>۳ پرونده فوری</small></div><div><span>درآمد این ماه</span><b>۸۴.۲ م</b><small>میلیون تومان</small></div><div><span>رضایت کاربران</span><b>۹۴٪</b><small>بر اساس ۲۱۴ نظر</small></div></div><div className="admin-grid"><div className="panel"><h2>درخواست‌های نیازمند اقدام</h2><DataList/></div><div className="panel chart"><h2>درخواست‌ها در ۷ روز اخیر</h2><div className="bars">{[42,63,48,76,58,89,70].map((n,i)=><i key={i} style={{height:n+"%"}}><span>{n}</span></i>)}</div></div></div></>;const titles:any={lawyers:"۷ وکیل منتظر بررسی",users:"۱٬۲۸۴ کاربر فعال",assign:"۳ پرسش بدون وکیل",content:"مقالات، خدمات و پرسش‌های متداول",finance:"تراکنش‌ها و کمیسیون",messages:"پیام‌های پشتیبانی"};return <div className="panel"><div className="panel-head"><div><h2>{titles[tab]}</h2><p>جزئیات، وضعیت و اقدامات مدیریتی این بخش.</p></div><button className="primary">+ افزودن مورد</button></div><DataList/></div>}
function DataList(){return <div className="data-list"><div><span className="status s0">نیازمند اقدام</span><div><b>مورد جدید ثبت‌شده</b><small>مدارک کامل · امروز ساعت ۱۰:۴۵</small></div><button>بررسی و اقدام ←</button></div><div><span className="status s2">در حال بررسی</span><div><b>درخواست شماره #۲۸۴۲</b><small>آخرین بروزرسانی ۲ ساعت پیش</small></div><button>مشاهده ←</button></div><div><span className="status s1">تکمیل شده</span><div><b>سابقه تکمیل‌شده</b><small>توسط مدیر اصلی</small></div><button>جزئیات ←</button></div></div>}

function Modal({name,close,selected,login,notify,go,answer}:any){const [accepted,setAccepted]=useState(false),[u,setU]=useState("client"),[p,setP]=useState("Client123!");if(name==="answer")return <div className="modal-wrap"><div className="modal answer-modal"><button className="x" onClick={close}>×</button><span className="topic">{answer.topic}</span><h2>{answer.q}</h2><div className="answer-lawyer"><Avatar lawyer={selected} small/><div><b>{answer.lawyer}</b><small>وکیل پایه یک دادگستری</small></div></div><div className="answer-box"><span>پاسخ وکیل</span><p>{answer.a}</p></div><small className="disclaimer">این پاسخ عمومی جایگزین بررسی دقیق پرونده نیست.</small><button className="primary wide" onClick={()=>{close();go("lawyers")}}>مشاوره با وکیل متخصص</button></div></div>;
 if(name==="login")return <div className="modal-wrap"><div className="modal login-modal"><button className="x" onClick={close}>×</button><Logo/><h2>خوش آمدید</h2><p>برای ادامه وارد حساب آزمایشی شوید.</p><div className="role-tabs">{["client","lawyer","admin"].map(k=><button key={k} className={u===k?"active":""} onClick={()=>{setU(k);setP(k==="client"?"Client123!":k==="lawyer"?"Lawyer123!":"Admin123!")}}>{k==="client"?"موکل":k==="lawyer"?"وکیل":"مدیر"}</button>)}</div><label>نام کاربری<input value={u} onChange={e=>setU(e.target.value)}/></label><label>رمز عبور<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label><button className="primary wide" onClick={()=>login(u,p)}>ورود به حساب</button><div className="demo-hint"><b>حساب‌های آماده تست</b><span>client / Client123!</span><span>lawyer / Lawyer123!</span><span>admin / Admin123!</span></div></div></div>;
 if(name==="ask")return <div className="modal-wrap"><form className="modal ask-modal" onSubmit={e=>{e.preventDefault();close();notify("پرسش شما ثبت شد و به وکلای مرتبط ارجاع می‌شود")}}><button type="button" className="x" onClick={close}>×</button><span className="topic">پرسش رایگان</span><h2>مسئله‌ات را کوتاه برایمان بنویس</h2><p>اطلاعات هویتی شما منتشر نمی‌شود.</p><label>موضوع<select required><option value="">انتخاب موضوع</option><option>خانواده و طلاق</option><option>کیفری</option><option>ملکی و قراردادها</option><option>سایر</option></select></label><label>شرح مسئله<textarea required minLength={20} maxLength={1200} rows={6} placeholder="چه اتفاقی افتاده و چه سؤالی دارید؟"/></label><label className="check"><input type="checkbox"/> اجازه انتشار نسخه بدون نام سؤال را می‌دهم.</label><button className="primary wide">ثبت و ارجاع رایگان</button></form></div>;
 const isPhone=name==="phone";return <div className="modal-wrap"><div className="modal pay-modal"><button className="x" onClick={close}>×</button><span className="topic">{isPhone?"مشاوره تلفنی":"گفت‌وگوی متنی"}</span><h2>رزرو با {selected.name}</h2><div className="mini-lawyer"><Avatar lawyer={selected} small/><div><b>{selected.field}</b><small>★ {selected.rating} · آماده پاسخ‌گویی</small></div><strong>{isPhone?selected.price:"۳۲۰ هزار تومان"}</strong></div><label>موضوع مشاوره<select><option>انتخاب موضوع</option><option>خانواده و طلاق</option><option>ملکی و قرارداد</option><option>کیفری</option></select></label><label className="check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> <span>با <button onClick={()=>notify("قوانین: اطلاعات محرمانه است؛ لغو تا ۲ ساعت قبل ممکن است.")}>قوانین و مقررات</button> موافقم.</span></label><button disabled={!accepted} className="primary wide" onClick={()=>{close();notify(isPhone?"رزرو موفق بود؛ به‌زودی با شما تماس می‌گیریم":"پرداخت آزمایشی موفق بود؛ گفت‌وگو در پنل فعال شد")}}>پرداخت آزمایشی و ثبت درخواست</button><small className="secure">در این نسخه مبلغی از حساب شما کسر نمی‌شود.</small></div></div>}
function Footer({go}:any){return <footer><div><Logo/><p>مسیر ساده و مطمئن برای رسیدن به پاسخ حقوقی درست.</p></div><div><b>دسترسی سریع</b><button onClick={()=>go("lawyers")}>همه وکلا</button><button onClick={()=>go("questions")}>پرسش‌های حقوقی</button><button onClick={()=>go("blog")}>مجله حقوقی</button></div><div><b>ارتباط با ما</b><p>۰۲۱-۹۱۰۹ ۲۰۲۰</p><p>تهران، میدان ونک</p><p>support@dadrah.ir</p></div><div><b>با خیال راحت</b><p>اطلاعات و مدارک شما محرمانه می‌ماند.</p><div className="trust-row"><span>نماد اعتماد</span><span>وکلای تأییدشده</span></div></div></footer>}
